[package]
name = "observer"
version.workspace = true
edition.workspace = true
description = "cluster orchestrator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
