[package]
name = "server"
version.workspace = true
edition.workspace = true
description = "core component of the message queue"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
