[package]
name = "shared_structures"
version.workspace = true
edition.workspace = true
description = "Shared structures between the Observer and Broker"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid.workspace = true
